# -*- coding: utf-8 -*-
"""NumPy_second_project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VMYrjYIwPrjQ1G6cwolRFOxNpGBfNCmv

##Step 1: Importing NumPy library
"""

import numpy as np

"""##Step 2: Read the data
For reading the data 1st we need to upload the data set into our google colab. After that we can just save the copy data path link or the name of the data set into a variable.

"""

data_file = '/content/KAG_Conversion_Data.csv'

"""##Step 3: Working On The Instructions

1. Load the data. Data is already given to you in variable path.
>
"""

#Loading the data set
data = np.genfromtxt(data_file, delimiter = ',', skip_header= 1)
#Printing the data
print('\nData: \n\n', data)

"""
2. How many unique ad campaigns (xyzcampaignid) does this data contain ? And for how many times was each campaign run ?

>- For solving this question 1st we need to extract the 'xyzcampaignid' column(xyzcampaignid is the column with index = 1) from the data set and saving it in a veriable called 'campaign'.
"""

#Extracting the 'xyzcampaignid' column in campaign.
campaign = data[:,1]
#printing out the no. of unique value present in campaign
print(len(np.unique(campaign)),'unique ad campaigns this data contain.')
#Now for the 2nd part of the question 1st we need to find out the unique values present in 'campaign'
print('Unique values of campaign are-',np.unique(campaign)) 
#And now we are going to find out how many times was each campaign run.
camp_916 = data[campaign== 916, ]
print('No. of 916 campaign run is -', camp_916.shape[0])
camp_936 = data[campaign==936, 1]
print('No. of 936 campaign run is -', camp_936.shape[0])
camp_1178 = data[campaign==1178, 1]
print('No. of 1178 campaign run is -', camp_1178.shape[0])

"""3. What are the age groups that were targeted through these ad campaigns?

>- In our the data set we have some column that have data type in string and age is also one of them so in this case we have to load our data in dtype = string than we can do the analysis.


"""

#Loading the data_file in string data type.
data_str = np.genfromtxt(data_file, delimiter =',', dtype = 'str', skip_header = 1)
#Extractin age column(age is the column with index = 3)
age = data_str[:,3]
#printing out the unique values of age column to see the targeted age groups
print(np.unique(age))
print('The age groups that were targeted through the ad campaigns are - 30 to 49.')

"""4. What was the average, minimum and maximum amount spent on the ads?

>- For solving this question 1st we need to extract the 'spent' column form the data set than we csn find out the average, minimum and maximum amount spent on the ads.


"""

#Extracting spent column(spent is the column with index = 8)
spent = data[:,8]
print('The average value spent on the ads is -',np.mean(spent))
print('The minimum value spent on the ads is -',np.min(spent))
print('The maximum value spent on the ads is -',np.max(spent))

"""#NumPy Mini Project
Let us work on a new project using NumPy. Where we are going to analys the data by following the given instructions.
For working on a new project we need a data set. In our case we have a data set called "KAG_Conversion_Data.csv".
##Features of the data set are given below:
1. ad_id:    unique ID for each ad
2. xyzcampaignid:    an ID associated with each ad campaign of XYZ company
3. fbcampaignid:    an ID associated with how Facebook tracks each campaign
4. age:    age of the person to whom the ad is shown
5. gender:    gender of the person to whom the add is shown
6. interest:    a code specifying the category to which the person’s interest belongs (interests are as mentioned in the person’s Facebook public profile)
7. Impressions:    the number of times the ad was shown
8. Clicks:    number of clicks on for that ad
9. Spent:    Amount paid by company xyz to Facebook, to show that ad
10. Total conversion:    Total number of people who enquired about the product after seeing the ad
11. Approved conversion:    Total number of people who bought the product after seeing the ad

##And in data set we have some instructions, those are given below:
- Load the data. Data is already given to you in variable path

- How many unique ad campaigns (xyzcampaignid) does this data contain ? And for how many times was each campaign run ?

- What are the age groups that were targeted through these ad campaigns?

- What was the average, minimum and maximum amount spent on the ads?

- What is the id of the ad having the maximum number of clicks ?

- How many people bought the product after seeing the ad with most clicks? Is that the maximum number of purchases in this dataset?

- So the ad with the most clicks didn't fetch the maximum number of purchases. Find the details of the product having maximum number of purchases

5. What is the id of the ad having the maximum number of clicks ?

>- So here 1st we need to extract the ad_id and clicks column and after that we need to find the max no. of clicks and compare it with the id column for find out id which having max click.
"""

#Extracting clicks column
clicks = data[:,7]
#Extracting ad_id column
ids = data[:,0]
#taking the max click in 'clicks' column
max_click = clicks.max()
print(max_click)
#taking all columns values which have max clicks
all_data_max_click = data[data[:,7] == 421]
print('The id of the ad having the mmaximum numbers of clicks is -', all_data_max_click[0][0])

"""6.  How many people bought the product after seeing the ad with most clicks? Is that the maximum number of purchases in this dataset?

>- We have already extracted clicks column and checked the maximum no. of click. So now we just need to extract the 'Approved_Conversion' column(Approved_Conversion) and compare with max_click. And after that we need to find maximum no of purchases and check it is equal to 


"""

purchases = data[:,10]
print(all_data_max_click[0][10],'people bought the product after seeing the ad with most click.')
# checking the max purchases
max_purchase = purchases.max()
if max_purchase == all_data_max_click[0][10]:
  print('True')
else:
  print('It is not the maximum number of purchases in this dataset.')

"""7. So the ad with the most clicks didn't fetch the maximum number of purchases. Find the details of the product having maximum number of purchases.

>- In here 1st we need to find out the maximum no. of purchases and take all the data by comparing the max. no. of purchases.


"""

# Maximum no. of purchases
max_purchase = purchases.max()
print('Maximum no. of purchases is -',max_purchase)
# Taking all the data which have maximum no. of purchases.
all_data = data_str[data[:,10] == 21]
print('the details of the product having maximum number of purchases is -', all_data)